"""Hardware-isolated reference implementation of impact-aware landing.

The package covers the rotor/reduced dynamics, impact reset, constrained NLP,
contact detection, leg admittance, correction-gain boundary, strict config,
and a pure command coordinator for the paper equations.  A low-rate executor
can submit leg targets to an already acquired Unitree LowCmd owner.  The host
side of the flight-controller residual protocol is implemented and locally
testable; matching FC firmware/transport and cross-device commit remain
deliberately unavailable for hardware.

中文说明：该包同时包含两层内容：一层是论文公式对应的三维离线数值基准，另一层是
面向当前传感器能力的法向简化模型与候选执行接口。这里导出的类和函数便于仿真、
回归和接口联调；它们不会自动绕过 HardwareWorld、LowCmd ownership 或飞控 residual
门禁。真实自动着陆链尚未组装完成，导入本包不等于取得任何执行器权限。
"""

from aerogo2.landing.impact_aware.aerogo2_normal_only import (
    AeroGo2NormalOnlyLandingFixture,
    build_aerogo2_normal_only_landing_fixture,
    solve_aerogo2_normal_only_landing,
)
from aerogo2.landing.impact_aware.aerogo2_offline import (
    AeroGo2OfflinePriorBundle,
    build_aerogo2_offline_prior_bundle,
    solve_aerogo2_offline_hover,
)
from aerogo2.landing.impact_aware.dynamics import (
    aggregate_contact_wrench,
    reduced_continuous_dynamics,
    reduced_discrete_step,
)
from aerogo2.landing.impact_aware.go2_kinematics import (
    HARDWARE_VALIDATED as GO2_KINEMATICS_HARDWARE_VALIDATED,
)
from aerogo2.landing.impact_aware.go2_kinematics import (
    OFFLINE_PRIOR_ONLY as GO2_KINEMATICS_OFFLINE_PRIOR_ONLY,
)
from aerogo2.landing.impact_aware.go2_kinematics import (
    SDK_LEG_ORDER,
    Go2KinematicsError,
    Go2LegKinematics,
    Go2UrdfKinematicJoint,
    Go2UrdfKinematics,
    load_go2_urdf_kinematics,
)
from aerogo2.landing.impact_aware.impact import (
    contact_transition_indicators,
    evaluate_impulse_constraints,
    foot_post_impact_velocity,
    impulses_world_to_body,
    integrate_contact_impulse,
    momentum_reset,
    sticking_constraint_satisfied,
    sticking_velocity_residual,
)
from aerogo2.landing.impact_aware.math_utils import (
    integrate_body_rotation,
    is_rotation_matrix,
    require_rotation_matrix,
    skew,
    so3_exp,
    total_com_C_linear_velocity_world_from_go2_body_origin_B,
    total_com_C_position_world_from_go2_body_origin_B,
    vee,
)
from aerogo2.landing.impact_aware.normal_admittance import (
    HARDWARE_OUTPUT_PERMITTED as NORMAL_ADMITTANCE_HARDWARE_OUTPUT_PERMITTED,
)
from aerogo2.landing.impact_aware.normal_admittance import (
    ContactLossPolicy,
    ForceObservation,
    ForceObservationMode,
    NormalAdmittanceConfig,
    NormalAdmittanceController,
    NormalAdmittanceError,
    NormalAdmittanceOutput,
    NormalAdmittanceState,
    NormalAdmittanceTransition,
    ResolvedNormalForce,
    resolve_normal_force,
)
from aerogo2.landing.impact_aware.normal_only_mpc import (
    NormalOnlyMPCProblem,
    NormalOnlyMPCResult,
    NormalOnlyMPCWeights,
    solve_normal_only_mpc,
)
from aerogo2.landing.impact_aware.preliminary import (
    GRAM_FORCE_TO_NEWTON,
    CadBomInertiaProperties,
    ContactModel,
    FixedXGeometryPrior,
    FlightControllerContractPrior,
    FootForceSemantics,
    ManufacturerThrottleThrustCurve,
    NormalOnlyVerticalState,
    PinnedGo2UrdfPrior,
    PreliminaryLandingModelConfig,
    PreliminaryModelError,
    ProvisionalMassProperties,
    ProvisionalOfflineInertiaEstimate,
    QuasiStaticRotorPrior,
    ScalarContactPrior,
    SdkCountContactDetection,
    SdkCountContactDetector,
    SdkCountContactDetectorConfig,
    StepCadSourceProvenance,
    calibrated_normal_force_scalars_n,
    compute_sdk_count_contact_detector_hash,
    ideal_arresting_normal_impulse_ns,
    ideal_level_hover_thrust_per_rotor_n,
    load_preliminary_landing_model,
    manufacturer_static_thrust_n_at_throttle,
    normal_only_vertical_acceleration_m_per_s2,
    normal_only_vertical_impact_reset,
    normal_only_vertical_step,
    recompute_preliminary_derived_document,
)
from aerogo2.landing.impact_aware.rotor import (
    build_fixed_deployed_allocation_matrix,
    evaluate_rotor_constraints,
    first_order_thrust_rate,
    first_order_thrust_step,
    rotor_wrench_body,
    thrust_and_reaction_torque,
)
from aerogo2.landing.impact_aware.types import (
    FOOT_COUNT,
    GO2_SDK_LEG_ORDER,
    ROTOR_COUNT,
    FixedDeployedRotorGeometry,
    FootLeverArmsFromComBody,
    FootLeverArmsFromComBodyHorizon,
    FootPositionsFromBodyOriginB,
    ImpactLimits,
    ImpulseConstraintResiduals,
    ReducedDynamicsConfig,
    ReducedInput,
    ReducedState,
    ReducedStateDerivative,
    RotorActuatorConfig,
    RotorAerodynamics,
    RotorConstraintResiduals,
    foot_positions_from_body_origin_B_to_com_lever_arms,
    four_foot_reorder_indices,
    validate_four_foot_leg_order,
)

__all__ = [
    "FOOT_COUNT",
    "GO2_SDK_LEG_ORDER",
    "ROTOR_COUNT",
    "CadBomInertiaProperties",
    "AeroGo2OfflinePriorBundle",
    "AeroGo2NormalOnlyLandingFixture",
    "ContactLossPolicy",
    "ContactModel",
    "FlightControllerContractPrior",
    "FixedXGeometryPrior",
    "FootForceSemantics",
    "ForceObservation",
    "ForceObservationMode",
    "FootLeverArmsFromComBody",
    "FootLeverArmsFromComBodyHorizon",
    "FootPositionsFromBodyOriginB",
    "GO2_KINEMATICS_HARDWARE_VALIDATED",
    "GO2_KINEMATICS_OFFLINE_PRIOR_ONLY",
    "GRAM_FORCE_TO_NEWTON",
    "Go2KinematicsError",
    "Go2LegKinematics",
    "Go2UrdfKinematicJoint",
    "Go2UrdfKinematics",
    "ImpactLimits",
    "ImpulseConstraintResiduals",
    "ManufacturerThrottleThrustCurve",
    "NORMAL_ADMITTANCE_HARDWARE_OUTPUT_PERMITTED",
    "NormalAdmittanceConfig",
    "NormalAdmittanceController",
    "NormalAdmittanceError",
    "NormalAdmittanceOutput",
    "NormalAdmittanceState",
    "NormalAdmittanceTransition",
    "ReducedDynamicsConfig",
    "ReducedInput",
    "ReducedState",
    "ReducedStateDerivative",
    "RotorActuatorConfig",
    "RotorAerodynamics",
    "RotorConstraintResiduals",
    "ResolvedNormalForce",
    "SDK_LEG_ORDER",
    "NormalOnlyVerticalState",
    "NormalOnlyMPCProblem",
    "NormalOnlyMPCResult",
    "NormalOnlyMPCWeights",
    "PinnedGo2UrdfPrior",
    "PreliminaryLandingModelConfig",
    "PreliminaryModelError",
    "ProvisionalMassProperties",
    "ProvisionalOfflineInertiaEstimate",
    "QuasiStaticRotorPrior",
    "ScalarContactPrior",
    "SdkCountContactDetection",
    "SdkCountContactDetector",
    "SdkCountContactDetectorConfig",
    "StepCadSourceProvenance",
    "FixedDeployedRotorGeometry",
    "aggregate_contact_wrench",
    "build_fixed_deployed_allocation_matrix",
    "build_aerogo2_offline_prior_bundle",
    "build_aerogo2_normal_only_landing_fixture",
    "calibrated_normal_force_scalars_n",
    "compute_sdk_count_contact_detector_hash",
    "contact_transition_indicators",
    "evaluate_impulse_constraints",
    "evaluate_rotor_constraints",
    "first_order_thrust_rate",
    "first_order_thrust_step",
    "foot_post_impact_velocity",
    "foot_positions_from_body_origin_B_to_com_lever_arms",
    "four_foot_reorder_indices",
    "impulses_world_to_body",
    "integrate_body_rotation",
    "integrate_contact_impulse",
    "is_rotation_matrix",
    "ideal_arresting_normal_impulse_ns",
    "ideal_level_hover_thrust_per_rotor_n",
    "load_preliminary_landing_model",
    "load_go2_urdf_kinematics",
    "manufacturer_static_thrust_n_at_throttle",
    "momentum_reset",
    "normal_only_vertical_acceleration_m_per_s2",
    "normal_only_vertical_impact_reset",
    "normal_only_vertical_step",
    "recompute_preliminary_derived_document",
    "reduced_continuous_dynamics",
    "reduced_discrete_step",
    "resolve_normal_force",
    "require_rotation_matrix",
    "rotor_wrench_body",
    "skew",
    "so3_exp",
    "solve_aerogo2_offline_hover",
    "solve_aerogo2_normal_only_landing",
    "solve_normal_only_mpc",
    "sticking_constraint_satisfied",
    "sticking_velocity_residual",
    "total_com_C_linear_velocity_world_from_go2_body_origin_B",
    "total_com_C_position_world_from_go2_body_origin_B",
    "thrust_and_reaction_torque",
    "validate_four_foot_leg_order",
    "vee",
]
